### ISSUE TITLE
Build runner doesn't work as expected

### ISSUE THREAD

**Issue by AmoonPod** [odroe/prisma-dart#99] opened 2023-01-10 08:30 UTC
After the v2.6.0, whenever I try to run `dart run build_runner build` it freeze at 94/95. I tried with `dart pub cache clean`, but it's still not working. I've also tried to upgrade to 2.6.1. 

![Screenshot 2023-01-10 alle 09 28 42](https://user-images.githubusercontent.com/80224270/211499751-69df4d82-4518-45bd-982d-209b47c666d5.png)
This is the terminal. 

![Screenshot 2023-01-10 alle 09 29 06](https://user-images.githubusercontent.com/80224270/211499846-3df7b597-3d4f-40ca-8f86-df988dd6baf4.png)
And I also get thousands of errors in the Dart Analysis tool, due to the Build Runner procedure not working. 

Any idea?

**Comment by AndryHTC** [comment] 2023-01-10 08:43
Same here
![image](https://user-images.githubusercontent.com/29896004/211502931-50f2883e-4f8f-4a53-9126-66bc64d28729.png)

**Comment by medz** [comment] 2023-01-10 09:35
@AndryHTC @AmoonPod I've investigated this issue, it's a freezed or build performance issue, currently I can't do anything about it, because there are too many clases generated via Prisma DMMF.

I have plans to fix this in Dart 3, because Dart 3 supports union types, and many type inputs also require union types.

The introduction of `freezed` in 2.6 is also because the 2.6 version plans to support all Prisma input types, including ref.

The result of my test is that it takes a long time to wait, but I haven't analyzed the cause of the specific lag in `dart run build_runner build`. My personal guess is that the Dart process is stuck because the prisma client has a lot of content and has reached the limit of a single Dart process.

Do you guys have a way of profiling `build`? Although this is a build performance issue, it is caused by `freezed`.

**Comment by medz** [comment] 2023-01-10 09:39
I have tried removing `freezed` and only using `json_serializable` but no such problem. But currently it is easiest to generate with union types support using `freezed`.

When Prisma DMMF is generated, I need to deal with a lot of content, and I am no longer able to develop the support of Union Types alone. None of this is a problem in Dart 3. And it can also reduce the template code by about 60%.

https://github.com/dart-lang/language/blob/master/working/union-types/nominative-union-types.md

**Comment by medz** [comment] 2023-01-10 09:50
rrousselGit/freezed#836

**Comment by medz** [comment] 2023-01-10 11:42
https://github.com/rrousselGit/freezed/issues/836#issuecomment-1377127594

@AndryHTC @AmoonPod One thing I can confirm is that this problem is caused by the performance of `freezed`, and `freezed` is needed to fix it.

**Comment by medz** [comment] 2023-01-10 11:47
Here are some suggestions to speed up the build:

Create a `build.yaml` file and add the `freezed` build configuration to reduce the build content:

```yaml
targets:
   $default:
     builders:
       frozen:
         options:
           copy_with: false
           equal: false
```

Then all you have to do is wait ⌛️, the `build` ecosystem isn’t great, but in Dart 2 we have no choice.

`freezed` is an essential component to currently support all of Prisma's input types, as it supports union types.

When Dart 3 is released, we will be much easier. With language-level support for macros and union types, Prisma Dart client no longer needs third-party libraries to complete boilerplate and serialization.

**Comment by medz** [comment] 2023-01-11 05:14
> @medz, took 2h 30m but I confirm the files are generated 🤣
> 
> EDIT: 4h 50m

I'm actively looking for an alternative to `freezed`, Dart 3 is a good fit, but we have a long wait.

I've searched for nearly three hours and couldn't find a similar package. And I can't solve this problem with `freezed`.

Let's discuss whether Prisma's full input type requirement should be withdrawn:

1. 😕 - Withdraw Prisma full input type
2. 👀 - Let's fix it in Dart 3

Other solutions are also welcome, but it is worth noting that Prisma's full input type must be supported, because Prisma ref fields will soon enter the official version. It can help us to compare based on fields, instead of manually entering values.

**Comment by jakub-stefaniak** [comment] 2023-01-14 12:18
Unfortunately, after switching to freezed working with this package is really time consuming. For now I will stay with version [2.4.7](https://pub.dev/packages/orm/versions/2.4.7), since it worked well for my purposes. It's much better to have only around 800 lines of code in .g file than additional 270k  in freezed. ( 170k after turning off copy_with and equal in build.yaml - which is many for 4 prisma models... )

**Comment by jackstefansky** [comment] 2023-01-14 12:23
Unfortunately after switching to freezed working with the package got really time consuming. I will stay with version [2.4.7](https://pub.dev/packages/orm/versions/2.4.7) since it was good enough for my purposes. It's better to have only 800 lines of code in g.dart file than having an additional freezed file containing 270k lines or 170k after turning off copy_withs and equals methods in build.yaml, which is a lot for just 4 pirsma models...

**Comment by medz** [comment] 2023-01-14 12:44
> Unfortunately after switching to freezed working with the package got really time consuming. I will stay with version [2.4.7](https://pub.dev/packages/orm/versions/2.4.7) since it was good enough for my purposes. It's better to have only 800 lines of code in g.dart file than having an additional freezed file containing 270k lines or 170k after turning off copy_withs and equals methods in build.yaml, which is a lot for just 4 pirsma models... I like having all dependecies up to date, but in this case it's just impossible for me to work with that

It is true that before 2.6, generated input types would selectively choose which type to use during the generation phase, and additional types would be discarded. The addition of `freezed` did bring performance issues, and the author of `freezed` does not seem to be actively maintaining `freezed`. We can only hope that Dart 3 will fix it by adding Union Types and removing `freezed`.

Let's look forward to Dart 3 ❤️

**Comment by medz** [comment] 2023-01-14 12:46
In Dart 3 I'm sure I can make small type definitions and do all the functionality of 2.6 and later.

**Comment by jackstefansky** [comment] 2023-01-14 12:49
Yes, I am really looking forward that too. I enjoy using this package and will follow on issues and new releases.

**Comment by medz** [comment] 2023-01-14 12:53
> Yes, I am really looking forward that too. I enjoy using this package and will follow on issues and new releases. Let's hope that there won't be any delays and dart 3 will come out in mid 2023

@jackstefansky I'm already watching the development version of Dart 3, and once Union Types is successfully implemented, I'll immediately start working on solving this problem with Dart 3, and then release the preview version.

**Comment by jackstefansky** [comment] 2023-01-30 09:34
@medz https://medium.com/dartlang/dart-3-alpha-f1458fb9d232

**Comment by medz** [comment] 2023-01-30 10:06
> @medz https://medium.com/dartlang/dart-3-alpha-f1458fb9d232 But, you've probably seen that, already

Yep, I have seen it. I'm waiting until Union Types which is the most important support for `freezed` removed. I'm already working on refactoring for the next major release.

**Comment by medz** [comment] 2023-02-17 11:05
@jackstefansky @AndryHTC @AmoonPod @aschulz90 

https://pub.dev/packages/orm/versions/3.0.0-beta.1

In this new beta version there are the following changes:

1. Temporarily disable the union types function (waiting for Dart 3 support)
2. Remove `freezed`
3. Remove all `dart run orm` commands

Upgrade Guide:

1. Install Node locally (make sure npm/yarn/pnpm) is available globally
2. Install the `prisma` CLI (e.g. NPM: `npm i prisma`)
3. Modify the `generator.provider` in your `schame.prisma`:
     ```prisma
     generator client {
         provider = "dart run orm"
     }
     ```
    > Use npm by default, if you want to change it, use `-p, --package-manager` parameter (e.g. use `pnpm`):
    > dart run orm -p pnpm
4. Run the generation command of Prisma CLI (npm as an example): `npx prisma generate`
5. Produce the `.g.dart` file: `dart run build_runner build`

**Note**: At present, only the test version has been released. The official version will be released after the 3.0 version is guaranteed to have no serious errors. At that time, a complete migration guide and new documents will be written.

**Comment by medz** [comment] 2023-02-17 11:07
```dart
import 'package:orm/logger.dart';
import 'package:orm/prisma_client.dart';

final prisma = PrismaClient(
  stdout: Event.values,
  datasources: Datasources(
    db: 'postgres://seven@localhost:5432/prisma-dart?schema=public',
  ),
);

void main() async {
  try {
    final fluent = prisma.user.findUniqueOrThrow(
      where: UserWhereUniqueInput(id: 1),
    );

    final user = await fluent;
    print(user);

    final count = await fluent.$count();
    print(count.posts);

    final posts = await fluent.posts();
    print(posts);

    final group = await prisma.user.groupBy(
      by: [UserScalarFieldEnum.id],
    );
    print(group.map((e) => e.toJson()));

    final aggregate = prisma.user.aggregate();
    print(await aggregate.$count().id());
    print(await aggregate.$avg().id());
    print(await aggregate.$min().name());
    print(await aggregate.$max().role());
    print(await aggregate.$max().createdAt());
  } finally {
    await prisma.$disconnect();
  }
}
```

Hope you enjoy the new Fluent API ❤️

**Comment by AndryHTC** [comment] 2023-02-17 12:14
@medz thank you for all your efforts. Can't wait to try, and even more to see the final version with Dart 3.0

**Comment by medz** [comment] 2023-02-27 07:09
https://prisma.pub/docs/migration-from-2.html

**Closed by medz** 2023-02-27 07:09 UTC
Labels: bug, done, dependencies, next-version-fix
