### ISSUE TITLE
dart run orm generate throws ProcessException: The system cannot find the file specified.

### ISSUE THREAD

**Issue by jackstefansky** [odroe/prisma-dart#129] opened 2023-02-28 17:29 UTC
After upgrade to orm: 3.0.0 running dart run orm generate gives me following error:

```
> dart run orm generate            

Unhandled exception:
ProcessException: The system cannot find the file specified.

Command: npm exec -- prisma version --json
```

which is strange because if I run `npm exec -- prisma version --json` it return I think correct output:

```
> npm exec -- prisma version --json
Environment variables loaded from .env
{
  "prisma": "4.11.0",
  "@prisma/client": "4.11.0",
  "current-platform": "windows",
  "query-engine-(node-api)": "libquery-engine 8fde8fef4033376662cad983758335009d522acb (at node_modules\\@prisma\\engines\\query_engine-windows.dll.node)",
  "migration-engine": "migration-engine-cli 8fde8fef4033376662cad983758335009d522acb (at node_modules\\@prisma\\engines\\migration-engine-windows.exe)",
  "format-wasm": "@prisma/prisma-fmt-wasm 4.11.0-57.8fde8fef4033376662cad983758335009d522acb",
  "default-engines-hash": "8fde8fef4033376662cad983758335009d522acb",
  "studio": "0.483.0"
}
```

also `npx prisma generate` does not generate prisma_client.dart. Just prints:
```
> npx prisma generate
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
```

**Comment by gutenfries** [comment] 2023-03-03 20:56
I have the same issue (also on windows), but neither `flutter clean` nor `dart pub cache clean` changed anything for me :(

**Comment by medz** [comment] 2023-03-04 04:07
I reopen it, this may be a long term concern.

>PS: I don't have a Windows device, it might take more scope to check exactly why it's happening. But I confirm it's not a code problem.

**Comment by nikosportolos** [comment] 2023-03-05 15:07
Looks like we need to run 'npm.cmd' instead of 'npm' to retrieve the Prisma version and platform on Windows.
I tried to modify the process in `bin/generator/prisma_info.dart:15` as a quick workaround and the `PrismaInfo` object was successfully initialized.

```dart
final result = Process.runSync(
      packageManager == 'npm' && Platform.isWindows ? 'npm.cmd' : packageManager,
      [
        'exec',
        if (packageManager == 'npm') '--',
        'prisma',
        'version',
        '--json',
      ],
      stdoutEncoding: convert.utf8,
    );
```

But even after solving that, the `prisma_client.dart` file is not generated as the process hangs on `bin/orm.dart:45`.
No events are received from the stdin stream in `bin/generator/generator.dart:37`, so the `Completer<Generator>()` never manages to complete.

@medz any hints or suggestions on this?

**Comment by medz** [comment] 2023-03-06 03:11
> Looks like we need to run 'npm.cmd' instead of 'npm' to retrieve the Prisma version and platform on Windows. I tried to modify the process in `bin/generator/prisma_info.dart:15` as a quick workaround and the `PrismaInfo` object was successfully initialized.
> 
> ```dart
> final result = Process.runSync(
>       packageManager == 'npm' && Platform.isWindows ? 'npm.cmd' : packageManager,
>       [
>         'exec',
>         if (packageManager == 'npm') '--',
>         'prisma',
>         'version',
>         '--json',
>       ],
>       stdoutEncoding: convert.utf8,
>     );
> ```
> 
> But even after solving that, the `prisma_client.dart` file is not generated as the process hangs on `bin/orm.dart:45`. No events are received from the stdin stream in `bin/generator/generator.dart:37`, so the `Completer<Generator>()` never manages to complete.
> 
> @medz any hints or suggestions on this?
> 
> **UPDATE** It seems that I was mistakenly running `dart run orm generate` instead of `npx prisma generate`. When I ran the latter the `prisma_client.dart` was successfully generated!

@nikosportolos Does yarn and pnpm have the same problem?

**Comment by nikosportolos** [comment] 2023-03-06 03:34
@medz Yes, I just installed and tried yarn and pnpm. They both needed the `*.cmd` file.
So I guess that line could change to:
```dart
Platform.isWindows ? '$packageManager.cmd' : packageManager,
```

**Comment by medz** [comment] 2023-03-06 04:12
@nikosportolos @jackstefansky 

https://github.com/odroe/prisma-dart/commit/64467396e6d1b6253f0e5b0bbc7f9f73a05257dc#diff-d46bd0e9b77bbb41f0ef1b4e5d1b801fb74009e301f1c7aa8ea7f2c40d36fa17R60

I've written a live-in lookup method that might solve this problem.

But I'm not closing this issue for now because I'm not sure about the global path separator on Windows.

The result I searched through Google is that WIndows splits the global path through `;`, and Unix splits it through `:` (I am sure about the split on Unix)

Since I don't have a Windows device, I can't confirm whether this fix works on Windows, can you verify it for me?

Authentication method:

1. `git clone https://github.com/odroe/prisma-dart && ce prisma-dart`
2. `npm install && dart pub get`
3. `npx prisma generate`

Check whether `lib/prisma_client.dart` is generated normally.

**Comment by medz** [comment] 2023-03-06 15:23
@nikosportolos @jackstefansky Version 3.0.2 fixes it, is it valid now?

**Comment by medz** [comment] 2023-03-06 15:26
> 



> I tried running dart run orm on 3.0.2 ref and it fails with:
> 
> ```
> Unhandled exception:
> ProcessException: %1 is not a valid Win32 application.
> 
> Command: "C:\Program Files\nodejs\npm" exec -- prisma version --json
> #0      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:487:7)
> #1      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:632:18)
> #2      Process.runSync (dart:io-patch/process_patch.dart:68:12)
> #3      new PrismaInfo.lookup (file:///C:/Users/stefp/AppData/Local/Pub/Cache/git/prisma-dart-28fe075d1f3a5c48115b70f5da4f85366d919015/bin/generator/prisma_info.dart:19:28)
> #4      main (file:///C:/Users/stefp/AppData/Local/Pub/Cache/git/prisma-dart-28fe075d1f3a5c48115b70f5da4f85366d919015/bin/orm.dart:47:27)
> #5      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
> #6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
> ```

Ok, I see, it seems the fix is not working.

I'll find a Windows device and within a day, I'll fix it!

You can manually specify the file address of npm with the -e parameter, hopefully it works 👉 https://prisma.pub/docs/configuration.html#node-package-manager-executable

**Comment by gutenfries** [comment] 2023-03-06 15:29
(@odroe @medz) perhaps this is out of scope for this project, but may I suggest GitHub Actions matrix testing?

The problems with this project seem to largely be around platform compatibility, and I feel that a quality CI server can help reduce the time that it takes to find, analyze, and correct these issues.

If you would like or require help in setting up CI matrix testing, you can feel free to assign me to an issue/PR :)

**Comment by medz** [comment] 2023-03-06 15:32
@gutenfries Thank you so much bro, I don't know anything about Windows. So I don't know where to go from here to handle it, plus I'm currently having trouble finding a Windows device to test on.

It would be great if you could handle that. Indeed this is a compatibility issue on Windows.

**Comment by nikosportolos** [comment] 2023-03-06 15:47
@medz Version 3.0.2 solved the package manager problem, but the `prisma_client.dart` is still not being generated.
I'll try to debug this a bit later in the day.

**Comment by medz** [comment] 2023-03-06 15:59
> @medz Version 3.0.2 solved the package manager problem, but the `prisma_client.dart` is still not being generated. I'll try to debug this a bit later in the day.

Thx 💗

**Comment by nikosportolos** [comment] 2023-03-06 18:54
On Windows we need to escape whitespaces in paths when running commands.
So if you tried to run
```shell
dart run orm -e C:\Program Files\nodejs\npm.cmd
```
it would fail, because of the whitespace in 'Program Files' with the error message: `Unable to find C:Program executable.`
In order to solve this, it needs to change to:
```shell
dart run orm -e "C:\Program Files\nodejs\npm.cmd"
```

So in the `schema.prisma` file we need to do the same, but the problem is that we can't have nested double quotes.
```
generator client {
  provider = "dart run orm -e "C:\Program Files\nodejs\npm.cmd""
}
```

An alternative would be to use `%PROGRAMFILES%\nodejs\npm.cmd` instead, but this fails to be recognised as a file on [bin/generator/prisma_info.dart:57](https://github.com/odroe/prisma-dart/blob/88e55b7296614ff63ae321c3d92c8131c93059b0/bin/generator/prisma_info.dart#L56).

**Comment by nikosportolos** [comment] 2023-03-06 19:05
**UPDATE**

@medz it seems that you've already fixed that, but I was using it the wrong way.  😅
We don't have to use the full path, but just the executable name instead:
```
generator client {
  provider = "dart run orm -e npm.cmd"
}
```

If anyone else can verify that this works, I think this issue can be marked as done.

**Comment by jackstefansky** [comment] 2023-03-06 19:37
> **UPDATE**
> 
> @medz it seems that you've already fixed that, but I was using it the wrong way. 😅 We don't have to use the full path, but just the executable name instead:
> 
> ```
> generator client {
>   provider = "dart run orm -e npm.cmd"
> }
> ```
> 
> If anyone else can verify that this works, I think this issue can be marked as done.

I can confirm - this works :)

**Comment by medz** [comment] 2023-03-06 22:22
I don't think this is a good fix, until it works with npm without passing any arguments it should be successful.

**Closed** 2023-03-07 02:53 UTC
Labels: bug, windows
