### ISSUE TITLE
feat: add a .fromJson method in the input classes

### ISSUE THREAD

**Issue by NazarenoCavazzon** [odroe/prisma-dart#42] opened 2022-10-03 23:50 UTC
![image](https://user-images.githubusercontent.com/49735945/193705615-7df64050-d333-4eda-a9dc-ae0ca4a7b50f.png)

**Comment by medz** [comment] 2023-01-03 04:00
#84

**Comment by medz** [comment] 2023-01-03 14:53
@NazarenoCavazzon The feat released in `2.5.0` version

**Comment by NazarenoCavazzon** [comment] 2023-01-03 14:53
Nice!

**Comment by NazarenoCavazzon** [comment] 2023-01-03 14:59
@medz the idea behind this was to be able to generate also the DTOs for the clases we have in the prisma schema, so that way it saves us a lot of time writing those.

**Comment by medz** [comment] 2023-01-03 15:03
> @medz the idea behind this was to be able to generate also the DTOs for the clases we have in the prisma schema, so that way it saves us a lot of time writing those.

@NazarenoCavazzon Yep, for RESTful server and GraphQL server, supporting the direct creation of input from JSON map can reduce a lot of unnecessary template code, thereby reducing the mental burden of developers.

**Comment by medz** [comment] 2023-01-03 15:07
@NazarenoCavazzon I'm personally dissatisfied with the current JSON serialization and deserialization, the mental model for writing input/outout classes is too big for me. This problem comes from `json_serializable`, I originally planned to get rid of it in 2.5.0, but `freezed` and `crimson` serialization support is not perfect, especially `freezed` toJson still relies on json_serializable.

Since I can't get rid of json_serializable, I think I'll wait until Dart 3 to try macros to get rid of json_serializable.

**Comment by NazarenoCavazzon** [comment] 2023-01-03 15:14
@medz Seems reasonable, dart right now gives a lot of problems with this.

**Comment by NazarenoCavazzon** [comment] 2023-01-04 00:46
@medz I'm testing Spry, overall looks amazing!, and looking at the documentation I found a typo.

![image](https://user-images.githubusercontent.com/49735945/210464524-b9da51f1-d25a-48b9-af8d-ab3c74d01fef.png)

The variable is named spray, not spry, also I found many spaces after a dot, could it be the translator?

**Comment by medz** [comment] 2023-01-04 05:58
> @medz I'm testing Spry, overall looks amazing!, and looking at the documentation I found a typo.
> 
> ![image](https://user-images.githubusercontent.com/49735945/210464524-b9da51f1-d25a-48b9-af8d-ab3c74d01fef.png)
> 
> The variable is named spray, not spry, also I found many spaces after a dot, could it be the translator?

It should be caused by the format tool, I will recheck the documentation and fix it, also welcome to submit a PR

The grammatical error should be caused by me, because my English writing ability is relatively poor.

**Comment by medz** [comment] 2023-01-05 04:54
@NazarenoCavazzon There is no serialization support for union in 2.5.*, which will cause normal dart run build_runner build to fail, I will reopen this issue. Then mark the 2.5. version as unavailable. Fixing this requires removing the built-in PrismaUnion and introducing the `freezed` package, after which I will release version 2.6.0.

**Closed** 2023-01-05 07:14 UTC
Labels: enhancement

**Comment by medz** [comment] 2023-01-05 07:19
Now, I released version 2.6.0 to fix the unsupported union serialization in 2.5.*. This version has changed a lot and supports the complete Prisma input requirements (the previous version will selectively choose the largest input parameter type). The formJson method is also fully supported now.

> I will mark the 2.5.* version as unavailable later to avoid the wrong use of the 2.5.* unavailable version, which will cause the program to always fail to run.

**Comment by NazarenoCavazzon** [comment] 2023-01-05 12:43
Niiiceeee
